import { background } from '@chakra-ui/styled-system'
import Head from 'next/head'
import Image from 'next/image'
import { About, MeetMe } from '../components/misc/about'
import { ImageBox } from '../components/misc/ImageBox'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import { Box } from '@chakra-ui/layout'
import { useColorModeValue } from '@chakra-ui/color-mode'
import { Animation } from '../components/Layouts/animation'
export default function Home() {
  const scrollColor=useColorModeValue('red','#212121')
  return (
    <Box transition='0.20s all ease-in-out'
      bg={useColorModeValue('#FFFCDC','gray.900')}
    >
      <Head>
        <title>Hello i am unda wotar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;400;500;700;800&display=swap" rel="stylesheet"/>
      </Head>
      <MeetMe />



        
    </Box>
  )
}
