import React from 'react'
import Navbar from '../Navbar'
import { Image } from '@chakra-ui/image'
import { Box } from '@chakra-ui/layout'
import { color, Container, Spacer, useColorModeValue } from '@chakra-ui/react'
import { Footer } from '../Footer'
import Head from 'next/head'
import { ImageBox } from '../misc/ImageBox'
import { Animation } from './animation'
import {Helmet} from 'react-helmet'
import { Cursor, cursor } from '../cursor'


function Layout({ children }) {
    const scrollColor = useColorModeValue('red','blue')
    const bg = useColorModeValue('#FFFCDC','gray.900')
    return (
        <>
        <Cursor/>
        <Box as='main' transition='0.2s' >
            <Head>
                <title>The_Binary_pagesV2.0</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Helmet bodyAttributes={{style:`background-color:${bg}`}}/>
            <Navbar/>
            <Box 
            
            >

                {children}
            </Box>
            <Footer/>
        </Box>
        </>
                
        

                
                
            
    )
}

export default Layout
